### ISSUE TITLE
AccessHandle proposal dates

### ISSUE THREAD

**Issue by hcldan** [fivedots/storage-foundation-api-explainer#32]
I see it's in an origin trial from 95-98... will it be removed form chrome or go live after that?
@fivedots

**Comment by fivedots** [comment]
The Storage Foundation trial is likely to expire by 98, and we don't intend to ship it.

We are currently pursuing Access Handles, and our intention is to ship after its origin trial, pending feedback on the trial and approvals from the appropriate owners.
